version: 0.2

phases:
  post_build:
    commands:
      - echo "Deploying ECS stack..."
      - IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c1-7)
      - |
        aws cloudformation deploy \
          --stack-name spring-cloud-fargate \
          --template-file infra/ecs/template.yml \
          --parameter-overrides \
            ParserServiceImage=897316073585.dkr.ecr.us-east-1.amazonaws.com/parser-service:$IMAGE_TAG \
            ProcessorServiceImage=897316073585.dkr.ecr.us-east-1.amazonaws.com/processor-service:$IMAGE_TAG \
          --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM