version: 0.2

phases:
  post_build:
    commands:
      - echo "Deploying ECS stack..."
      - aws cloudformation deploy --stack-name spring-cloud-fargate --template-file infra/ecs/template.yml --parameter-overrides ParserServiceImage=parser-service:latest --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
