Parameters:
  GitHubToken:
    Type: String
    NoEcho: true

Resources:

  PipelineArtifactBucket:
    Type: AWS::S3::Bucket

  # IAM role for CodeBuild projects
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: CodeBuildPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:GetObjectVersion
                  - s3:GetBucketLocation
                Resource:
                  - !Sub "arn:aws:s3:::${PipelineArtifactBucket}"
                  - !Sub "arn:aws:s3:::${PipelineArtifactBucket}/*"
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:CompleteLayerUpload
                  - ecr:UploadLayerPart
                  - ecr:InitiateLayerUpload
                  - ecr:PutImage
                Resource: "*"
              - Effect: Allow
                Action:
                  - secretsmanager:GetSecretValue
                Resource:
                  - arn:aws:secretsmanager:us-east-1:897316073585:secret:docker-hub-username*
                  - arn:aws:secretsmanager:us-east-1:897316073585:secret:docker-hub-password*
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource: "*"



  # Parser Service CodeBuild Project
  ParserServiceBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: ParserServiceBuilder
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: parser-service/buildspec.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: DOCKER_HUB_USERNAME
            Type: SECRETS_MANAGER
            Value: arn:aws:secretsmanager:us-east-1:897316073585:secret:docker-hub-username-1WZeNo
          - Name: DOCKER_HUB_PASSWORD
            Type: SECRETS_MANAGER
            Value: arn:aws:secretsmanager:us-east-1:897316073585:secret:docker-hub-password-BBwR48

      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: /aws/codebuild/ParserServiceBuilder

  # Processor Service CodeBuild Project
  ProcessorServiceBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: ProcessorServiceBuilder
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: processor-service/buildspec.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: DOCKER_HUB_USERNAME
            Type: SECRETS_MANAGER
            Value: arn:aws:secretsmanager:us-east-1:897316073585:secret:docker-hub-username-1WZeNo
          - Name: DOCKER_HUB_PASSWORD
            Type: SECRETS_MANAGER
            Value: arn:aws:secretsmanager:us-east-1:897316073585:secret:docker-hub-password-BBwR48

      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: /aws/codebuild/ProcessorServiceBuilder

  # IAM role for CodePipeline
  PipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSCodeBuildDeveloperAccess
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryPowerUser

  DeployBuild:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: DeployEcsStack
      ServiceRole: !GetAtt CodeBuildRole.Arn
      Source:
        Type: CODEPIPELINE
        BuildSpec: infra/cicd/deploy-buildspec.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:7.0
        Type: LINUX_CONTAINER
      LogsConfig:
        CloudWatchLogs:
          Status: ENABLED
          GroupName: /aws/codebuild/DeployEcsStack

  # CI/CD Pipeline
  CICDPipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt PipelineRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineArtifactBucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: 1
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: MishaGaal
                Repo: spring-cloud-fargate
                Branch: master
                OAuthToken: !Ref GitHubToken
        - Name: Build
          Actions:
            - Name: BuildParser
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: !Ref ParserServiceBuild

            - Name: BuildProcessor
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: !Ref ProcessorServiceBuild
        - Name: Deploy
          Actions:
            - Name: DeployEcs
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              InputArtifacts:
                - Name: SourceOutput
              Configuration:
                ProjectName: !Ref DeployBuild
