version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Docker Hub..."
        - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
        - echo "Logging in to Amazon ECR..."
        - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 897316073585.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t processor-service:latest -f processor-service/Dockerfile .
      - docker tag processor-service:latest 897316073585.dkr.ecr.us-east-1.amazonaws.com/processor-service:0.0.1
      - echo "Pushing Docker image to ECR..."
      - docker push 897316073585.dkr.ecr.us-east-1.amazonaws.com/processor-service:0.0.1

  post_build:
    commands:
      - echo "Deploying ECS service via CloudFormation..."