version: 0.2

phases:
  install:
    commands:
      - echo "Dependencies already installed in CodeBuild image..."
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo "Building Maven project..."
      - chmod +x mvnw
      - ./mvnw clean install
      - echo "Building Docker image..."
      - docker build -t processor-service:latest ./processor-service
  post_build:
    commands:
      - echo "Deploying ECS service via CloudFormation..."
      - aws cloudformation deploy \
        --stack-name spring-cloud-fargate \
        --template-file ../infra/ecs/template.yml \
        --parameter-overrides ProcessorServiceImage=processor-service:latest \
        --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
