version: 0.2

phases:
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 123456789012.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Logging in to Docker Hub...
      - echo $DOCKER_HUB_PASSWORD | docker login --username $DOCKER_HUB_USERNAME --password-stdin
      - docker build -t mishagaal/parser-service .
      - docker push mishagaal/parser-service
      - echo "Building Docker image..."
      - docker build -t parser-service:latest -f parser-service/Dockerfile .

  post_build:
    commands:
      - echo "Deploying ECS service via CloudFormation..."
      - aws cloudformation deploy \
        --stack-name spring-cloud-fargate \
        --template-file $CODEBUILD_SRC_DIR/infra/ecs/template.yml \
        --parameter-overrides ParserServiceImage=parser-service:latest \
        --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM
